### PR TITLE
Gridview filter datetime picker

### PR DESCRIPTION
**Pull request by xaerobiont**
Hi again!
It's uncomfortably to use plain text inputs to filter pages by created and updated time fields.
I want to suggest you little enhancement - use [kartik-v/yii2-date-range](https://github.com/kartik-v/yii2-date-range). It's very useful widget for picking date and time intervals.

### CODE REVIEW

**Comment by bupy7** [comment]
Such modifications are individual for each. I may not merge your the pull-request.

You can override your the view and add this the date-range widget.

**Comment by xaerobiont** [comment]
As you wish, it was just a suggestion.
Anyway I believe that end user wants to get maximum "from the box" and plain text input as a datetime filtration field is absolutely unusable for anyone.

**Comment by bupy7** [comment]
@zvook In my extensions I do not impose superfluous solutions. Only minimum for solve of a task. And subject of 'datetime' can not be resolve at few lines of code. This broad topic with time zone, date/time format and uncoupling from third party a extensions. Many developer are not using a widgets or they using AngularJs, Backbone and etc. Client-side must be clean as much as possible. And one the extension must decide only one a task. Not more.

**Comment by xaerobiont** [comment]
@bupy7 your truth. But I think we should give to end user "something" with **poossibility** of customize this something as he want, instead of "nothing" with **necessity** to customize this nothing to get something :)

**Comment by bupy7** [comment]
@zvook I do not practice "all from the box" an approach. And a user can customizing all part of my extension via `controllerMap` or `themes`.

**Pull request closed without merging**
